### ISSUE TITLE
City should not be required

### ISSUE THREAD

**Issue by philipkcl** [culturesofknowledge/emlo-project#80]

**Comment by philipkcl** [comment]
@mirandalewis if city fields is not required, is there have any fields required for create location?
![image](https://user-images.githubusercontent.com/97410502/204506922-1187dcc0-12d7-4c18-8a2a-e67fd028db56.png)

**Comment by mirandalewis** [comment]
Dear Philip,

No, we decided that no field for the locations should be required.

This is because we knew we might need any combination of the fields to best describe a place, and that if we were too restrictive we would not be able to create, for example, a record for a place that had a name, is known to have existed but does not exist now (it could have been a building or a small village, for example) and while an authoritative article might exist for it that we can reference, no one is certain of its exact location. So we decided we have to allow flexibility. It is best to allow for cases like this and be flexible even though records such as this example do not occur very often.

Thank you for asking.

All very best,
Miranda

**Comment by philipkcl** [comment]
Thanks for reply @mirandalewis.
In the current development stage, could have more questions and emails than usual.
those questions would be help for confirm the system requirements.

It's could be a lot email but please don't mind, and those questions are not urgent. So, please free feel to reply it.

**Comment by mirandalewis** [comment]
Hi Philip,

Not a problem about queries. I’ll be travelling from early tomorrow and not back until Monday, but I’ll pick up emails whenever I can.

Keep well and thanks so much for all your attention to detail with our EMLO.
All very best,
Miranda
